version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/apps/api'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/apps/ui'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'terraform'
    directory: '/infra/terraform'
    schedule:
      interval: 'weekly'
